<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class DefaultPageContentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $distanceSellingContract = '
            <p><b>[YOUR_COMPANY_NAME] ONLINE ÜYELİK SÖZLEŞMESİ VE KULLANIM KOŞULLARI<br></b></p>
            <p.&nb><b>Madde 1.&nbsp;&nbsp;</b>&nbsp; Taraflar İşbu [YOUR_COMPANY_NAME] Yatak Ve Yorgan Sanayi Ticaret Anonim Şirketi Online Üyelik Sözleşmesi ve Kullanım Koşulları (kısaca “Sözleşme”) www.[WEBSITE_DOMAIN].com.tr uzantılı web sitesinin ve buna bağlı tüm uygulamaların (kısaca “Site”) tüm haklarının sahibi olan [YOUR_COMPANY_NAME] Yatak Ve Yorgan Sanayi Ticaret Anonim Şirketi (kısaca “[YOUR_COMPANY_NAME]”) ile kimlik ve iletişim bilgilerini işbu Sözleşme’nin kabulü öncesinde sisteme tanımlamış olan veya tanımlamamış olsa dahi Site’den ürün satın alan Müşteri arasındadır.</p>
            <p><b>Madde 2.&nbsp;</b>&nbsp;&nbsp; Sözleşme’nin Konusu İşbu Sözleşme’nin konusu [YOUR_COMPANY_NAME]’ın sahibi olduğu platform üzerinden ürün satın alma imkanının sağlanması ve tarafların karşılıklı hak ve yükümlülüklerinin belirlenmesidir. Müşteri, Site\'ye Müşteri olarak veya Müşteri olmaksızın Site’den alışveriş yapması halinde, işbu Sözleşme’nin tamamını okuduğunu, anladığını ve tüm hükümlerini onayladığını kabul, beyan ve taahhüt eder.</p>
            <p><b>Madde 3.&nbsp;</b>&nbsp;&nbsp;<b> [YOUR_COMPANY_NAME]’nın Hakları</b></p>
            <p><b>3.1.&nbsp;</b>&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME], güvenlik nedeniyle Müşteri’nin Site üzerindeki her türlü aktivitesini izleyebilir, kayda alabilir ve/veya gerekli gördüğünde, Site\'den uzaklaştırma, Müşterilik dondurma, Müşterilik iptal etme ve benzeri her türlü müdahalede bulunabilir.</p>
            <p><b>3.2.</b>&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME], önceden Müşteri’ye bildirimde bulunmaksızın Site\'nin biçim ve içeriğini kısmen ve/veya tamamen değiştirebileceği gibi, Site\'nin yayın yaptığı alan adını değiştirebilir, farklı alt alan adları kullanabilir, alan adı yönlendirmesi yapabilir ve/veya alan adını kapatabilir.</p>
            <p><b>3.3.&nbsp;&nbsp;</b>&nbsp;&nbsp; [YOUR_COMPANY_NAME], dilediği zamanda ve/veya sebep göstermeksizin, önceden Müşteri\'ye bilgi vermeksizin Site\'de sunduğu hizmetlerin kapsam ve/veya çeşitlerini değiştirebileceği gibi, Site\'de sunulan hizmetleri kısmen veya tamamen dondurabilir, sona erdirebilir veya tamamen iptal edebilir.</p>
            <p><b>3.4.</b>&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME], Sözleşme’de belirtilen iş ve/veya işlemlerin daha etkin gerçekleştirilebilmesi açısından dilediği zaman hizmet, satış şartları ve/veya işleyişte değişiklikler ve/veya güncellemeler yapabilir. Müşteri’ler işbu değişiklikleri kabul ettiklerini, bu değişikliklere uygun davranacaklarını şimdiden kabul ve beyan ederler.</p>
            <p><b>3.5.</b>&nbsp;&nbsp;&nbsp;&nbsp; İşbu Sözleşme [YOUR_COMPANY_NAME] ürün satışı için herhangi bir taahhüt içermez. Müşteri, bu ve sair nedenlerle [YOUR_COMPANY_NAME]’dan hiçbir ad altında hak ve alacak talep edemez.</p>
            <p><b>3.6.</b>&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME]’nın Müşteri’nin Site’ye üye olması halinde üyeliği tek taraflı olarak durdurma, sona erdirme ve/veya iptal etme hakkı mevcuttur. Müşteri bu hususta herhangi bir itiraz hakkının mevcut olmadığını kabul, beyan ve taahhüt eder.</p>
            <p><b>3.7.</b>&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME], 6698 sayılı Kanun hükümleri uyarınca aydınlatma yükümlülüğü ve gerekmesi halinde rıza alma yükümlüklerini yerine getirmek ve sair güvenlik önlemlerine uymak şartıyla kullanıcı profili ve pazar araştırmaları yapmak, satış ve site kullanım istatistikleri oluşturmak gibi amaçlar dahil ancak bunlarla sınırlı olmamak üzere tüm yasal amaçlar için, Müşteri\'nin kimlik, adres, iletişim ve site kullanım bilgilerini bir veri tabanında toplayabilir ve bu bilgileri işleyebilir. Ayrıca [YOUR_COMPANY_NAME] bu bilgileri, yasaların getirdiği zorunluluklara uyma amacıyla veya yetkili adli veya idari otoritenin yürüttüğü soruşturma veya araştırma açısından talep edilmesi durumunda veya kullanıcıların hak ve güvenliklerinin korunması amacıyla üçüncü kişi/kurumlarla paylaşabilir.</p>
            <p><b>3.8.&nbsp;</b>&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME] sisteminde satışa sunulan ürünlerin ve hizmetlerin fiyat ve ürün özellik bilgilerini değiştirme yükümlülüğü [YOUR_COMPANY_NAME]’ya aittir.&nbsp;</p>
            <p><b>3.9.&nbsp;</b>&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME], ileride doğacak teknik zaruretler ve mevzuata uyum amacıyla kullanıcıların aleyhine olmamak kaydıyla işbu Sözleşme’nin uygulamasında değişiklikler yapabilir, mevcut maddelerini değiştirebilir veya yeni maddeler ilave edebilir.</p>
            <p><b>3.10.&nbsp;</b>&nbsp; Müşteri tarafından veya sadece referans kolaylığı nedeniyle [YOUR_COMPANY_NAME] tarafından link verilmiş ise bu [YOUR_COMPANY_NAME]’nın verilen linklerin yöneldiği internet sitelerini desteklemek amacıyla verilmiş olduğu anlamında yorumlanamaz veya [YOUR_COMPANY_NAME] tarafından söz konusu internet sitesi veya içeriğine yönelik herhangi bir beyan veya garanti verildiği şeklinde kabul edilemez. Bu şekilde erişilen siteler, dosyalar ve içerikler ile ilgili [YOUR_COMPANY_NAME] hiçbir sorumluluk kabul etmez.&nbsp;<br></p>
            <p><b>Madde 4.&nbsp;&nbsp;&nbsp; Müşteri’nin Yükümlülükleri</b></p>
            <p><b>4.1.&nbsp;&nbsp;</b>&nbsp;&nbsp; Müşteri üye olmak isterse üyeliği, Site’de belirtilen üyelik prosedürünün yerine getirilerek kayıt işleminin yapılması ile tamamlanır. Müşteri, üye olmakla, işbu Sözleşme hükümlerini, üyeliğe ve hizmetlere ilişkin [YOUR_COMPANY_NAME] tarafından açıklanan/açıklanacak her türlü beyanı da kabul etmiş olmaktadır.</p>
            <p><b>4.2.&nbsp;&nbsp;</b>&nbsp;&nbsp; Müşteri, işlemlerinde belirtmiş olduğu kimlik, ödeme bilgileri, adres ve/veya iletişim bilgilerinin eksiksiz ve doğru olduğunu, bilgilerinde değişiklik olması halinde bu bilgileri derhal yazılı olarak [YOUR_COMPANY_NAME]’a ileteceğini, eksik, güncel olmayan ve/veya yanlış bilgi vermesi nedeniyle ortaya çıkabilecek her türlü hukuki uyuşmazlık ve/veya zarardan sadece kendisinin sorumlu olacağını kabul ve beyan eder. [YOUR_COMPANY_NAME]’a bu nedenle hiçbir sorumluluk izafe edilemez.</p>
            <p><b>4.3.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri, üye olması halinde madde 4.2’de yer alan bilgilere ek olarak üyelik işlemlerinde belirtmiş olduğu bilgilerinin doğru ve eksiksiz olduğunu, bilgilerinde değişiklik olması halinde bu bilgileri derhal yazılı olarak [YOUR_COMPANY_NAME]’a ileteceğini, siparişlerinin vermiş olduğu bilgilere uygun olarak düzenleneceğini, bilgilerin eksik ve/veya yanlış olarak belirtmesi nedeniyle ortaya çıkabilecek sorunlar her türlü hukuki uyuşmazlık ve/veya zarardan sadece kendisinin sorumlu olacağını kabul ve beyan eder. [YOUR_COMPANY_NAME]’a bu nedenle hiçbir sorumluluk izafe edilemez.<span id="selectionBoundary_1629830634293_26212829840825935" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span></p>
            <p><b>4.4.&nbsp;&nbsp;</b>&nbsp;&nbsp; Müşteri, Site’de belirtilen hizmetlerden faydalanırken T.C. yasalarına ve genel ahlak kurallarına uygun hareket edeceğini, hakaret, tehdit, iftira, taciz ve benzeri eylemlerde bulunmayacağını, siyasi ve/veya ideolojik propaganda yapmayacağını, diğer Müşteri\'leri rahatsız edici davranışlar içine girmeyeceğini, kişi ve/veya kurumları lekeleyici her türlü davranıştan uzak duracağını ve Site\'de verilen hizmetlerin aksamasına ya da kesilmesine neden olabilecek her türlü hareketten kaçınacağını, aksi halde oluşacak her türlü zarardan bizzat sorumlu olacağını kabul ve taahhüt eder.</p>
            <p><b>4<span id="selectionBoundary_1629830625148_3435867965894257" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span>.5.&nbsp;&nbsp;</b>&nbsp;&nbsp; Müşteri, üçüncü şahısların fikri mülkiyet hukuku kapsamındaki haklarını ihlal etmeyeceğini, üçüncü kişilerin telif haklarına saygılı olacağını, haksız rekabette bulunmayacağını ve üçüncü şahısların ticari sırlarına ve özel hayatlarına saygılı olacağını kabul ve taahhüt eder.</p>
            <p><b><span id="selectionBoundary_1629830615297_11982790308235391" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span>4.6.&nbsp;&nbsp;<span id="selectionBoundary_1629830615297_2678026694737836" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span></b>&nbsp;&nbsp; Müşteri, Site\'yi kullanırken başkaları tarafından kolay tahmin edilemeyecek bir şifre kullanacağını, kullanıcı adı, şifre ve benzeri bilgilerini başkalarıyla paylaşmayacağını ve bu güvenliğinden bizzat ve sadece kendisinin sorumlu olacağını, hiçbir şekilde [YOUR_COMPANY_NAME]’ın sorumlu olmayacağını kabul ve beyan eder.</p>
            <p><b>4.7.</b>&nbsp;&nbsp;&nbsp;&nbsp; Müşteri, hileli davranışlarda bulunmayacağını, Site\'nin güvenlik mekanizmasına müdahale etmeyeceğini aksi halde oluşabilecek her türlü zarardan sorumlu olduğunu ve [YOUR_COMPANY_NAME]’ın uğrayacağı tüm zararları karşılayacağını taahhüt eder.</p>
            <p><b>4.8.</b>&nbsp;&nbsp;&nbsp;&nbsp; Müşteri, üye olması halinde sadece kendisine ait üyelik hesabını kullanacağını, başka Müşterilerin hesap bilgilerini kullanmayacağını ve/veya kendisine ait üyelik hesabını başkalarına kullandırtmayacağını, aksi durumun [YOUR_COMPANY_NAME] tarafından tespit edilmesi halinde üyeliğinin ve teslim edilmemiş siparişlerinin iptal edilebileceğini ve doğmuş/doğacak her türlü zararı tazmin edeceğini kabul ve beyan eder.</p>
            <p><b>4.9.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri, Site\'ye, zararlı program, yazılım, kod ve/veya benzeri materyal göndermeyeceğini veya paylaşmayacağını, Site\'nin ve diğer Müşterilerin güvenliğini tehlikeye düşürebilecek her türlü hareketten kaçınacağını kabul ve taahhüt eder.</p>
            <p><b>4.10.&nbsp;</b>&nbsp; Müşteri, işbu Sözleşmeden doğan hak ve yükümlülükleri ve Site’ye üye olması halinde üyelik hesabını üçüncü kişilere devredemez.&nbsp;</p>
            <p><b>4.11.&nbsp;</b>&nbsp; Müşteri, başkalarının Site’yi kullanımını kısıtlayamaz, engel olamaz ve Site’nin veya Site’yi kullanılabilir hale getirmek için kullanılan sunucu veya ağların işletimine müdahale edemez.</p>
            <p><b>4.<span id="selectionBoundary_1629830579477_6677317348498073" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span>12.</b>&nbsp;&nbsp; Müşteri’nin, bilgisayar donanımını etkileyen virüs saldırılarından ve/veya Site’den edindiği bilgiler sebebiyle veya Site’ye erişimine ve kullanımına ilişkin olarak doğrudan veya dolaylı olarak meydana gelebilecek zararlardan [YOUR_COMPANY_NAME] sorumlu değildir.</p>
            <p><b>4.13.&nbsp;&nbsp;</b> Müşteri, Site çalışmasına müdahale etmek veya müdahaleye teşebbüs etmek amacıyla herhangi bir alet, yazılım ve/veya araç kullanmayacağını, Site’ye yetkisiz olarak bağlanmayacağını ve işlem yapmayacağını, diğer internet kullanıcılarının yazılımlarına ve verilerine izinsiz olarak ulaşmayacağını veya bunları kullanmayacağını kabul eder.1.14.&nbsp;&nbsp; Müşteri, Site üzerinden satın alınan ürünlerin kişisel kullanım amaçlı olduğunu, bunların tekrar satış amaçlı olmadığını kabul eder.</p>
            <p><b>4.15.&nbsp;&nbsp; </b>Müşteri, Site üzerinden gerçekleştirdiği siparişi iptal etmek istemesi halinde bu talebini kendisine belirtilecek şekilde siparişin verilmiş olduğu saatten itibaren en geç 24 (yirmi dört) saat içerisinde bildireceğini kabul, beyan ve taahhüt eder. [EHB1]&nbsp;Teslim edilen ürünlerin iadesinde Ön Bilgilendirme Metni, Mesafeli Satış Sözleşmesi ve ilgili mevzuat hükümleri uygulanacaktır.</p>
            <p><b>4.16.</b>&nbsp;&nbsp; &nbsp;Müşteri, Site üzerinden yaptığı her türlü iş ve işlemin sorumluluğunun kendisine ait olduğunu; burada gerçekleştirilen iş ve işlemleri kendisinin gerçekleştirmediği yolunda herhangi bir def’i ve/veya itiraz ileri süremeyeceğini ve/veya bu def’i veya itiraza dayanarak yükümlülüklerini yerine getirmekten kaçınmayacağını kabul, beyan ve taahhüt eder.</p>
            <p><b>4.17.&nbsp;&nbsp; </b>Müşteri, farklı bir kullanıcı adı kullanmak suretiyle birden fazla üyelik hesabı açmamayı kabul, beyan ve taahhüt eder. Bu kuralın ihlali veya herhangi bir sebeple üyelikten çıkarılan, üyeliği durdurulan veya askıya alınan birisinin tekrar Siteye girmek için farklı bir kullanıcı adı ile bir veya daha fazla üyelik hesabı açtığının, [YOUR_COMPANY_NAME] tarafından tespit edilmesi halinde, [YOUR_COMPANY_NAME]’ın, bu kişinin tüm üyelik hesapları, herhangi bir ihtara gerek olmaksızın iptal etme ve işbu sözleşmeyi herhangi bir tazminat yükümlülüğü olmadan tek taraflı olarak feshetme yetkisi olacaktır.<br></p>
            <p><b>Madde 5.&nbsp;&nbsp;&nbsp; Ödeme ile İlgili Koşullar</b></p>
            <p><b>5.1.&nbsp;&nbsp;</b>&nbsp;&nbsp; Müşteri, satın alacağı ürünlerin ücretini kredi kartı veya havale/EFT ile ödeyebilir.&nbsp;</p>
            <p><b>5.2.&nbsp;&nbsp;</b>&nbsp;&nbsp; Müşteri, satın alınan ürünlerin bedellerinin seçilen ödeme aracı ile ödemek zorunda olduğunu aksi takdirde hizmetlerin kendisine teslim edilmeyeceğini kabul eder.&nbsp;</p>
            <p><b>5.3.&nbsp;&nbsp;&nbsp;</b>&nbsp; Müşteri, online ödeme yöntemi sırasında verilecek kart bilgilerinin doğruluğundan sorumlu olup, [YOUR_COMPANY_NAME]’ın ödemeyi, kendi adı ve hesabına tahsil ettiğini bildiğini ve satış ilişkisinin kendisi ile [YOUR_COMPANY_NAME] arasında kurulmuş olacağını bildiğini kabul ve beyan eder.&nbsp;</p>
            <p><b>5.4.&nbsp;&nbsp;</b>&nbsp;&nbsp; Online ödeme yöntemi seçeneği kullanılarak yapılan ödemelerde, kartın hamili haricinde bir başkası tarafından hukuka aykırı şekilde kullanılması halinde Banka Kartları ve Kredi Kartları Kanunu ve Banka Kartları ve Kredi Kartları Hakkında Yönetmelik hükümlerine göre işlem yapılır. Online ödeme yöntemi ile ödemesi yapılmış siparişlerde, sipariş karşılığı fiş/fatura siparişi alan [YOUR_COMPANY_NAME] tarafından düzenlenir.<br></p>
            <p><b>Madde 6.&nbsp;&nbsp;&nbsp; Kişisel Verilerin Gizliliği ve Ticari Elektronik İleti</b></p>
            <p><b>6.1.&nbsp;&nbsp;&nbsp;</b>&nbsp; &nbsp;&nbsp; [YOUR_COMPANY_NAME], Müşteri’nin adı-soyadı, adresi, telefon numarası, kredi kartı bilgileri vb. Müşteri’yi tanımlamaya yönelik her türlü kişisel veriyi 6698 sayılı Kanun hükümleri uyarınca aydınlatma yükümlülüğü ve gerekmesi halinde rıza alma yükümlüklerini yerine getirmek ve sair güvenlik önlemlerine uymak şartıyla toplama, saklama, aktarma gibi her türlü işleme işlemini yapmaya yetkilidir.</p>
            <p><b>6.2.</b>&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME], kişisel bilgileri kesinlikle özel ve gizli tutmayı, bunu bir sır saklama yükümlülüğü olarak addetmeyi ve gizliliğin sağlanması ve sürdürülmesi, gizli bilginin tamamının veya herhangi bir kısmının kamu alanına girmesini veya yetkisiz kullanımını veya üçüncü bir kişiye ifşasını önlemek için gerekli tüm tedbirleri almayı ve gerekli özeni göstermeyi taahhüt etmektedir.&nbsp;</p>
            <p><b>6.3</b>.&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME]’nın gerekli bilgi güvenliği önlemlerini almasına karşın, Site\'ye ve sisteme yapılan saldırılar sonucunda gizli bilgilerin zarar görmesi veya üçüncü kişilerin eline geçmesi durumunda, [YOUR_COMPANY_NAME]’nın herhangi bir sorumluluğu olmayacaktır.</p>
            <p><b>6.4.<span id="selectionBoundary_1629830780748_7157182537983584" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span>&nbsp;&nbsp;</b>&nbsp;&nbsp; [YOUR_COMPANY_NAME] sunucularında toplanan bu bilgiler, aydınlatma yükümlülüğü kapsamında belirlenen amaçlar için kullanılacaktır.&nbsp;</p>
            <p><b>6.5.</b>&nbsp;&nbsp;&nbsp;&nbsp; Kişisel bilgiler içermeyen istatistiksel veriler [YOUR_COMPANY_NAME] çalışanları, iş ortakları gibi ifa yardımcıları ile paylaşılabilir.</p>
            <p><b>6.6.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri bilgileri, resmi makamlarca usulü dairesinde bu bilgilerin talep edilmesi halinde ve yürürlükteki emredici mevzuat hükümleri gereğince resmi makamlara açıklama yapmak zorunda olduğu durumlarda resmi makamlara açıklanabilecektir.&nbsp;</p>
            <p><b>6.7.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri, kişisel verilerinin işlenip işlenmediğini, işlenme amacını, verilerin aktarıldığı üçüncü kişileri, verilerin düzeltilmesini, silinmesini, anonim hale getirilmesini veya yok edilmesini, aykırı olarak işlenmiş ise zararın giderilmesini her zaman talep edebilir ve bilgi alabilir.&nbsp;</p>
            <p><b>6.8.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri, işbu Sözleşme’yi kabul ederek, [YOUR_COMPANY_NAME]’nın “Gizlilik ve Güvenlik Politikası” ve “Kişisel Verilerin Korunması Politikası” bölümünü de okuduğunu ve anladığını kabul eder.&nbsp;</p>
            <p><b>6.9.&nbsp;&nbsp;&nbsp;&nbsp;</b> Müşteri, izin vermesi halinde aynı zamanda [YOUR_COMPANY_NAME]’nın indirim ve hediye gibi promosyonlar ile promosyon amaçlı yarışma veya oyunlar dahil olmak üzere her türlü ticari elektronik veri, ses ve görüntü içerikli iletilerin telefon, çağrı merkezi, otomatik arama, elektronik posta, kısa mesaj hizmeti gibi vasıtalar kullanılarak iletebileceğini kabul ve beyan eder. <br></p>
            <p><b>Madde 7.&nbsp;&nbsp;&nbsp; Fikri Mülkiyet Hakları</b></p>
            <p><b>7.1.</b>&nbsp;&nbsp;&nbsp;&nbsp; Site’nin sunumu ve tüm içeriği T.C. Mevzuatı ve fikri mülkiyet mevzuatı tarafından korunmakta olup, bu Site’deki tüm ticari markalar, logolar ve hizmet işaretleri başta olmak üzere, yayınlanan tüm bilgi ve/veya veriler [YOUR_COMPANY_NAME]’a veya sözleşme yoluyla [YOUR_COMPANY_NAME]’a lisans verenlere aittir. Müşteri, [YOUR_COMPANY_NAME]’ın yazılı onayı olmadan, doğrudan ve/veya dolaylı olarak aynen ya da başka bir şekilde Site’nin içeriğini dağıtamaz, iletemez, değiştiremez, kopyalayamaz, görüntüleyemez, çoğaltamaz, yayınlayamaz, işleyemez ve/veya başka bir şekilde kullanamaz ve/veya başkasının Site\'nin hizmetlerine erişmesine ve/veya kullanmasına izin veremez. Aksi takdirde, [YOUR_COMPANY_NAME]’ın uğradığı/uğrayacağı her türlü zarar ile lisans verenler de dahil ancak bunlarla sınırlı olmaksızın, üçüncü kişilerin uğradıkları zararlardan dolayı [YOUR_COMPANY_NAME]’dan talep edilen her türlü tazminat tutarını, Müşteri, [YOUR_COMPANY_NAME]’a derhal ödemekle sorumlu olacaktır.</p>
            <p><b>7.2.&nbsp;&nbsp;&nbsp;</b>&nbsp; [YOUR_COMPANY_NAME]’ın, Site hizmetleri, Site bilgileri, Site\'nin telif haklarına tabi çalışmaları, Site\'nin ticari markaları, Site\'nin ticari görünümü ve/veya Site\'ye ilişkin her türlü maddi ve/veya fikri mülkiyet hakları da dahil tüm malvarlığı, ayni ve/veya şahsi hakları, ticari bilgi ve/veya know-how\'a yönelik tüm hakları saklıdır.</p>
            <p><b>7.3.&nbsp;&nbsp;&nbsp;</b>&nbsp; Site’de yer alan bütün yazıların, grafiklerin, görsellerin ve/veya tüm resimlerin her hakkı saklıdır, izinsiz tasarruf edilemez.</p>
            <p><b>7.4.</b>&nbsp;&nbsp;&nbsp;&nbsp; Site içeriğine, tasarımına ve/veya yazılımına ilişkin tüm mali hakların izinsiz kullanımı (işleme, çoğaltma, yayma, temsil ve umuma arz) bunlarla sınırlı olmamak üzere her türlü izinsiz ifşa ve/veya kullanım, fikri ve sınai mülkiyet haklarının ihlali anlamına gelecektir.</p>
            <p><b>7.5.</b>&nbsp;&nbsp;&nbsp;&nbsp; Müşteri’ler Site\'nin kullanımında Türk Borçlar Kanunu, Türk Ceza Kanunu, Fikir ve Sanat Eserleri Kanunu, Türk Ticaret Kanunu ve mevcut ve/veya ileride yürürlüğe girecek olan her türlü mevzuat hükümlerine uygun davranacaklarını kabul ve taahhüt ederler. Aksi kullanım sebebiyle doğabilecek hukuki, idari, cezai ve mali her türlü sorumluluk Müşteri’ye ait olup [YOUR_COMPANY_NAME]’ın rücu hakkı saklıdır.<br></p>
            <p><b>Madde 8.&nbsp;&nbsp;&nbsp; Sorumluluk</b></p>
            <p><b>8.1.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri, Site’de sunulan/yayınlanan bilgi ve/veya hizmetlerde eksiklik, iletişim sorunları, teknik problemler, altyapı ve/veya internet arızaları, elektrik kesintisi ve/veya sayılanlarla sınırlı olmaksızın başkaca problemler olabileceğini kabul etmekte olup, bu tür problemler/arızalar oluşması durumunda [YOUR_COMPANY_NAME] gerek satış başlamadan önce, gerek satış esnasında veya satış yapılmış olsa dahi Müşteri’ye herhangi bir bildirimde bulunmaya gerek olmaksızın ve/veya sebep göstermeksizin satışı durdurmaya ve/veya sona erdirmeye ve/veya iptal etmeye yetkilidir. Müşteri bu nedenlerle [YOUR_COMPANY_NAME]’dan hiçbir ad altında hak ve ödeme talep edemez.</p>
            <p><b>8.2.&nbsp;&nbsp;&nbsp;</b>&nbsp; [YOUR_COMPANY_NAME] hizmetin hatasız olacağını veya sürekli sağlanacağını veya hizmetin virüs ve diğer zararlı unsurlardan arınmış olduğunu garanti etmemektedir.</p>
            <p><b>8.3.&nbsp;&nbsp;</b>&nbsp;&nbsp; [YOUR_COMPANY_NAME]’ın ağır kusuru veya kastı haricinde, Müşteri’nin doğrudan ve/veya dolaylı zararlarından sorumluluğu bulunmamaktadır.<br></p>
            <p><b>Madde 9.&nbsp;&nbsp;&nbsp; Sözleşme’nin Feshi</b></p>
            <p><b>9<span id="selectionBoundary_1629830931699_7982912014162071" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span>.1.&nbsp;&nbsp;&nbsp;</b>&nbsp; Müşteri\'nin işbu Sözleşme’den kaynaklanan yükümlülüklerinden herhangi biri ve/veya tamamına kısmen ve/veya tamamen aykırı davranması durumunda [YOUR_COMPANY_NAME], herhangi bir bildirime gerek olmaksızın ve/veya gerekçe göstermeksizin tek taraflı olarak işbu Sözleşme’yi feshederek Site’ye üye olmuşsa Müşteri\'nin üyeliğini iptal edebilir ve Müşteri\'nin Site’den aldığı, almakta olduğu ya da alacağı hizmetleri kısmen veya tamamen dondurulabilir veya iptal edebilir. Bu nedenle fesih durumunda Müşteri [YOUR_COMPANY_NAME]’dan hiçbir hak ve/veya talepte bulunamaz. [YOUR_COMPANY_NAME]’ın doğmuş/doğacak her türlü zararını Müşteri’den talep etmeye yetkilidir.&nbsp;</p>
            <p><b><span id="selectionBoundary_1629830957545_4607772040867961" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span>9.2.&nbsp;&nbsp;<span id="selectionBoundary_1629830957545_7647408373423754" class="rangySelectionBoundary" style="line-height: 0; display: none;">﻿</span></b>&nbsp;&nbsp; Taraflar, işbu Sözleşme’yi dilediği takdirde hiçbir sebep göstermeksizin ve herhangi bir bildirime gerek olmaksızın tek taraflı olarak feshederek Müşteri Site’ye üye olmuşsa üyeliği iptal etmeye yetkilidir. Bu takdirde Müşteri haksız, yersiz, sebepsiz, mehilsiz ve zamansız bir fesihte bulunulduğu, iyi niyete aykırı davranıldığı veya sair bir neden ve bahane öne sürerek [YOUR_COMPANY_NAME]’dan hiçbir hak, alacak, kar kaybı, zarar ziyan tazminatı veya başkaca bir nam ve unvan altında herhangi bir ödeme talep edemez.<br></p
            <p><b>Madde 10.&nbsp;&nbsp;&nbsp; Sözleşme’nin Süresi</b></p>
            <p>İşbu Sözleşme Site’de onaylandığı andan itibaren yürürlüğe girer ve [YOUR_COMPANY_NAME]’ın veya Müşteri’nin üyeliğini iptal etmesi ve/veya Müşteri tarafından verilen siparişin iptal edilmesi ve/veya Müşteri tarafından verilen siparişin sorunsuz bir şekilde teslim edilmesi ve/veya Site’de sunulan hizmetleri sona erdirmesi ile birlikte başkaca bildirime gerek olmaksızın kendiliğinden sona erer.<br></p>
            <p><b>Madde 11.&nbsp;&nbsp;&nbsp; Muhtelif Hükümler</b></p
            <p><b>11.1.&nbsp;</b>&nbsp;&nbsp;&nbsp; Müşteri, Sözleşme ve hizmetlerde yapılacak değişikliklerin, satış ile ilgili hususların, üye olması halinde üyeliğinin iptalinin, işbu Sözleşme’nin feshinin, sona erdirilmesinin ve benzeri her türlü bildirimin işlemler esnasına belirttiği e-posta adresine yapılmasına muvafakat etmiş olup, e-posta ile yapılan bildirimler ulaşsın veya ulaşmasın bildirimin [YOUR_COMPANY_NAME] tarafından gönderildiği andan itibaren tebliğ edilmiş olduğunu ve hukuki sonuçlarını doğuracağını kabul ve taahhüt eder. Bildirimin Müşteri’ye geç ulaşması veya ulaşmamasından ve sonuçlarından [YOUR_COMPANY_NAME] sorumlu değildir.</p>
            <p><b>11.2.&nbsp;</b>&nbsp;&nbsp;&nbsp; İşbu Sözleşme’nin herhangi bir hükmünün, herhangi bir nedenden dolayı geçersiz sayılması veya uygulanabilirliğinin kalmaması halinde, Sözleşme’nin diğer hükümleri yürürlükte kalacaktır.</p
            <p><b>11.3.</b>&nbsp;&nbsp;&nbsp;&nbsp; [YOUR_COMPANY_NAME]’ın Sözleşme tahtında sahip olduğu herhangi bir hak veya yetkiyi kullanmaması ya da kullanmakta gecikmesi o hak veya yetkiden feragat ettiği anlamına gelmediği gibi, bir hak veya yetkinin tek başına veya kısmen kullanılması o veya başka bir hak veya yetkinin daha sonra kullanılmasını engellemez, feragat anlamı taşımaz.&nbsp;</p>
            <p><b>11.4.&nbsp;</b>&nbsp;&nbsp;&nbsp; İşbu Sözleşme’den doğan uyuşmazlıkların çözümü hususunda İstanbul Mahkemeleri ile İcra Daireleri yetkilendirilmiştir.</p>
            <p><b>11.5sp;&nbsp;</b>&nbsp;&nbsp; Müşteri Site’de yer alan tüm uygulama ve kuralları okuyup anladığını ve kabul ettiğini beyan eder. Müşteri, Sözleşme’nin tamamında yer alan menfaatlerine aykırı olabilecek düzenlemeleri de sonuçlarını bilerek ve anlayarak kabul ettiğini beyan eder.<br></p>
        ';

        $exchangeReturnAssembly = '
        <p><b>Teslimat</b></p>
        <p>Ev tekstili siparişlenizin kargoya verilme süresi ortalama 24 saattir. Yatak siparişlerinizin teslim süresi yaşadığınız şehre ve ürünün stok durumuna göre ortalama 5-24 iş günüdür. Siparişlerim bölümünden sürecinizi takip edebilirsiniz. Sorularınız için&nbsp;Sıkça Sorulan Sorular&nbsp;sayfasını ziyaret ediniz.</p>
        <p><b>İade &amp; Değişim</b></p>
        <p>Ürünün adresinize teslim tarihinden itibaren 14 gün içinde iade başvurusunda bulunarak sürecinizi başlatabilirsiniz. Ürünü iade etmek için, orijinal kutusuyla ve faturasıyla birlikte göndermelisiniz. İadenizin kabul edilmesi için, ürünün hasar görmemiş, kurulumunun yapılmamış ve kullanılmamış olması gerekmektedir. Sorularınız için&nbsp;İade ve Değişim&nbsp;bölümünü ziyaret ediniz.<br></p>
        ';

        $useOfPersonalData = '
        <p><b>İNTERNET SİTESİ KİŞİSEL VERİLERİN İŞLENMESİ AYDINLATMA METNİ</b><br></p>
        <p>İşbu Aydınlatma Metni 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) ve Aydınlatma Yükümlülüğünün Yerine Getirilmesinde Uyulacak Usul ve Esaslar Hakkında Tebliğ kapsamında [YOUR_ADDRESS] adresinde mukim [YOUR_COMPANY_NAME] tarafından Veri Sorumlusu sıfatıyla hazırlanmış ve sizlere sunulmuştur.</p>
        <p><b>KİŞİSEL VERİLERİN İŞLENME AMACI&nbsp;</b></p>
        <p>Şirketimize ait ; [YOUR_WEBSITE] &nbsp;internet sitesinden üyelik oluşturarak veya oluşturmadan alışveriş yapmanız halinde; Kimlik (Ad-soyadı, Cinsiyet), İletişim (E-posta, Adres, Telefon Numarası)&nbsp; kategorisindeki kişisel verileriniz kurumsal iletişim ve itibar yönetimi, sipariş yönetimi, etkinlik yönetimi, satış ağı yönetimi, müşteri ilişkileri yönetimi, ana veri oluşturma, bilgi güvenliği, muhasebe ve finans, marka araştırması, finans ve muhasebe operasyonları süreçlerinde Şirketimiz tarafından yürütülen ticari faaliyetlerin gerçekleştirilmesi için ilgili iş birimlerimiz tarafından gerekli çalışmaların yapılması ve buna bağlı iş süreçlerinin yürütülmesi, Şirketimiz tarafından sunulan ürün ve hizmetlerden ilgili kişileri faydalandırmak için gerekli çalışmaların iş birimlerimiz tarafından yapılması ve ilgili iş süreçlerinin yürütülmesi, Şirketimiz tarafından sunulan ürün ve hizmetlerin ilgili kişilerin beğeni, kullanım alışkanlıkları ve ihtiyaçlarına göre özelleştirilerek ilgili kişilere önerilmesi ve tanıtılması için gerekli olan aktivitelerin planlanması ve icrası, Şirketimizin ve Şirketimizle iş ilişkisi içerisinde olan ilgili kişilerin hukuki, teknik, ticari ve iş güvenliğinin temini sağlamak amacıyla [EHB2]&nbsp;hukuka ve dürüstlük kurallarına ve işlendikleri amaçla bağlantılı, sınırlı ve ölçülü, ilgili mevzuatta öngörülen veya işlendikleri amaç için gerekli olan süre kadar muhafaza edilme ilkelerine uygun olarak işlenecektir.</p>
        <p><b>KİŞİSEL VERİLERİN TOPLANMA YÖNTEMİ ve HUKUKİ SEBEBİ</b></p>
        <p>İşbu Aydınlatma Metninde belirtilen kişisel verileriniz Şirketimize ait ; [YOUR_WEBSITE] internet adresi aracılığıyla elektronik ortamda toplanmakta ve KVKK’nın 5. Maddesinde yer alan Bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, sözleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması hukuki sebebine dayanarak tamamen ya da kısmen otomatik yolla işlenmektedir. Kişisel verilerinizin işlenmesi ilgili kişi olarak sizlerin açık rızasına tabi olduğu durumlarda ise (Kampanya içerikli sms ve e-posta gönderilmesi yoluyla ürün / hizmetlerin Pazarlama Süreçlerinin Yürütülmesi) kişisel verileriniz KVKK’nın 5. Maddesinde belirtilen ilgili kişinin açık rızasının bulunması hukuki sebebine dayanarak tamamen ya da kısmen otomatik yolla işlenmektedir.</p>
        <p><b>KİŞİSEL VERİLEN AKTARILMASI</b></p>
        <p>Söz konusu kişisel verileriniz Şirketimiz tarafından sadece yukarıda belirtilen amaç dahilinde işlenmekte, KVKK’nın 8. Maddesinde belirtilen şartlar dahilinde şirketimizce gerçekleştirilemeyen ve uzmanlık gerektiren hususların yerine getirilmesi amacıyla hizmet/destek/danışmanlık alınan ya da işbirliği yapılan kurum ve kuruluşlarla ve resmi mercilerin talepleri nedeniyle yetkili kamu kurum ve kuruluşlarıyla paylaşılabilecektir.Söz konusu kişisel verileriniz bu husus haricinde Şirketimiz tarafından veri güvenliğine ilişkin alınması gereken her türlü idari ve teknik tedbir alınarak muhafaza edilmekte, üçüncü kişilerle paylaşılmamakta, satılmamaktadır.</p>
        <p><b>KİŞİSEL VERİLERİN SİLİNMESİ, YOK EDİLMESİ VEYA ANONİM HALE GETİRİLMESİ</b></p>
        <p>KVKK’nın 7. maddesi uyarınca, kişisel verilerinizin ilgili mevzuata uygun olarak işlenmiş olmasına rağmen, işlenmesini gerektiren sebeplerin ortadan kalkması halinde kişisel verileriniz re’sen veya talebiniz üzerine Şirketimiz tarafından silinir, yok edilir veya anonim hale getirilir. Bu hususa ilişkin usul ve esaslar KVKK ve 28.10.2017 tarihli ve 30224 sayılı Resmi Gazete’de yayınlanan Kişisel Verilerin Silinmesi, Yok Edilmesi veya Anonim Hale Getirilmesi Hakkında Yönetmelik’e göre yerine getirilecektir. Kişisel verileriniz, Şirketimiz tarafından silme, yok etme veya anonim hale getirme yükümlülüğümüzün ortaya çıktığı tarihi takip eden 6 (altı) ay içerisinde silinir, yok edilir veya anonim hale getirilir.&nbsp;</p>
        <p><b>KİŞİSEL VERİLERİN KORUNMASI KANUNU’NDAN DOĞAN HAKLARINIZ&nbsp;</b></p>
        <p>Kişisel veri sahibi olarak sizler KVKK’nın 11. Maddesinde belirtilen haklara sahipsiniz. Söz konusu haklarınızı Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ’e uygun şekilde [YOUR_ADDRESS] adresine yazılı olarak iletmek suretiyle kullanılabilirsiniz.</p>
        ';

        $privacySecurityAgreement = '
            <p style="text-align: center;"><strong><span>GİZLİLİK VE GÜVENLİK POLİTİKASI</span></strong></p>
            <p><span>[YOUR_COMPANY_NAME], </span><span>öncelikle müşterilerine ve üyelerine güvenli bir alışveriş ortamı sağlamayı ilke edinmiş bir firma olarak çeşitli amaçlarla kişisel veriler toplayabilir. Toplanan kişisel verilerin nasıl ve ne şekilde toplandığına, bu verilerin nasıl ve ne şekilde korunduğuna ilişkin olarak ve 6698 sayılı Kanun’dan doğan haklarınız ve haklarınızı nasıl kullanacağınıza yönelik detaylı bilgi için Kişisel Verilerin Korunması Politikasını inceleyebilirsiniz.&nbsp;</span></p>
            <p><span>Üyelerimiz veya müşterilerimiz tarafından [YOUR_WEBSITE] </span><span>uzantılı web sitesinin ve buna bağlı tüm uygulamaların</span><span> (<em>“</em></span><strong><em><span>İnternet Sitesi</span></em></strong><em><span>”</span></em><span>) elektronik ortamdan iletilen kişisel bilgiler, belirlenen amaçlar ve kapsam dışında üçüncü kişilere açıklanmayacaktır.</span></p>
            <p><strong><span>KREDİ KARTI GÜVENLİĞİ</span></strong></p>
            <p><span>İnternet Sitesi’nden alışveriş yapan</span><span> kartı sahiplerinin güvenliğini önemsemekteyiz. Kredi kartı bilgileriniz hiçbir şekilde sistemimizde saklanmamaktadır. Bu &nbsp;bilgiler sadece ödeme sayfasında, bankadan ödeme onayı alımında kullanılacaktır.</span></p>
            <p><span>Alışveriş sırasında kullanılan kredi kartı ile ilgili bilgiler alışveriş sitelerimizden bağımsız olarak SSL (Secure Sockets Layer) protokolü ile şifrelenip sorgulanmak üzere ilgili bankaya ulaştırılır. Kartın kullanılabilirliği onaylandığı takdirde alışverişe devam edilir. Kartla ilgili hiçbir bilgi tarafımızdan görüntülenemediğinden ve kaydedilmediğinden, üçüncü şahısların herhangi bir koşulda bu bilgileri ele geçirmesi engellenmiş olur.</span></p>
            <p><strong><span>WEB SİTESİ-ZİYARETCİ HABERLEŞME GÜVENLİĞİ</span></strong></p>
            <p><span>İnternet Sitesi’nin sipariş sayfalarında site ile ziyaretçi arasındaki haberleşme SSL standardında gerçekleşmektedir. Kredi kartı bilgilerinin verileceği sırada sayfada bu haberleşme biçiminin bulunup bulunmadığı, ödeme sayfasına erişildiğinde adres çubuğunda yazan ifadenin http:// biçiminde değil, " https:// " biçiminde oluşu ifade etmektedir. Bu nitelikteki sayfalara eriştiğinizde tarayıcının sağ alt köşesinde kilit ikonu da yer almaktadır.</span></p>
            <p><strong><span>ÜÇÜNCÜ TARAF WEB SİTELERİ VE UYGULAMALAR</span></strong></p>
            <p>İnternet<span> Sitesi, </span><span>web sitesi dâhilinde başka sitelere link verebilir. </span><span>[YOUR_COMPANY_NAME]</span><span>, bu linkler vasıtasıyla erişilen sitelerin gizlilik uygulamaları ve içeriklerine yönelik herhangi bir sorumluluk taşımamaktadır. İnternet Sitesi’nde yayınlanan reklamlar, reklamcılık yapan iş ortaklarımız aracılığı ile kullanıcılarımıza dağıtılır. </span><span>İnternet Sitesi’nde yer alan </span><span>Gizlilik Ve Güvenlik Politikası ile Kişisel Verilerin Korunması Politikası sadece </span><span>İnternet Sitesi </span><span>kullanımına ilişkindir ve üçüncü taraf web sitelerini kapsamaz.&nbsp;</span></p>
            <p><strong><span>E-POSTA GÜVENLİĞİ</span></strong></p>
            <p><span>İnternet Sitesi</span><span>Müşteri Hizmetleri’ne herhangi bir siparişinizle ilgili olarak göndereceğiniz e-postalarda, kredi kartı numaranızı veya şifrelerinizi yazmayınız. E-postalarda yer alan bilgiler üçüncü şahıslar tarafından görülebilir. </span><span>[YOUR_COMPANY_NAME]</span><span>, e-postalardan aktarılan bilgilerin güvenliğini hiçbir koşulda garanti etmemektedir.</span></p>
            <p><strong><span>TARAYICI ÇEREZLERİ&nbsp;</span></strong></p>
            <p><span>[YOUR_COMPANY_NAME]</span><span>,<span>&nbsp; </span></span><span>İnternet Sitesi’ni</span><span> ziyaret eden kullanıcılar ve kullanıcıların web sitesini kullanımı hakkındaki bilgileri teknik bir iletişim dosyası (Çerez-Cookie) kullanarak elde edebilir. Bahsi geçen teknik iletişim dosyaları, ana bellekte saklanmak üzere bir internet sitesinin kullanıcının tarayıcısına (browser) gönderdiği küçük metin dosyalarıdır. Teknik iletişim dosyası site hakkında durum ve tercihleri saklayarak internetin kullanımını kolaylaştırır.</span></p>
            <p><span>Teknik iletişim dosyası, &nbsp;siteyi kaç kişinin ziyaret ettiğini, bir kişinin siteyi hangi amaçla, kaç kez ziyaret ettiğini ve ne kadar sitede kaldıkları hakkında istatistiksel bilgileri elde etmeye ve kullanıcılar için özel tasarlanmış kullanıcı sayfalarından &nbsp;dinamik olarak reklam ve içerik üretilmesine yardımcı olur.</span></p>
            <p><span>[YOUR_COMPANY_NAME]</span><span>, işbu Gizlilik ve Güvenlik Politikası hükümlerini dilediği zaman sitede yayımlamak veya kullanıcılara elektronik posta göndermek suretiyle değiştirebilir. Gizlilik ve Güvenlik Politikası hükümleri değiştiği takdirde, yayımlandığı tarihte yürürlük kazanır.</span></p>
            <p><span>Gizlilik ve Güvenlik Politikası ile ilgili her türlü soru ve önerileriniz için </span><span>[YOUR_CUSTOMER_DESK_EMAIL_ADDRESS]</span><span> adresine e-posta gönderebilirsiniz veya aşağıdaki iletişim bilgilerinden </span><span>[YOUR_COMPANY_NAME]</span><span>’ne ulaşabilirsiniz.</span></p>
            <p><span>&nbsp;</span></p>
            <p><strong><span>Ticaret Unvanı</span></strong></p>
            <p><strong><span>: </span></strong><span>[YOUR_COMPANY_NAME]</span></p>
            <p><strong><span>Adres</span></strong></p>
            <p><span>: [YOUR_ADDRESS]</span></p>
            <p><strong><span>E-posta</span></strong></p>
            <p><span>: [YOUR_CUSTOMER_DESK_EMAIL_ADDRESS]</span></p>
            <p><strong><span>Telefon</span></strong></p>
            <p><strong><span>:</span></strong><span>&nbsp;</span><span>[YOUR_CONTACT_FORM]</span></p>
        ';

        Page::create([
            'title' => 'Mesafeli Satış Sözleşmesi',
            'content' => $distanceSellingContract,
        ]);

        Page::create([
            'title' => 'Değişim & İade, Montaj',
            'content' => $exchangeReturnAssembly,
        ]);

        Page::create([
            'title' => 'Kişisel Verilerin Kullanılması',
            'content' => $useOfPersonalData,
        ]);

        Page::create([
            'title' => 'Gizlilik & Güvenlik Sözleşmesi',
            'content' => $privacySecurityAgreement,
        ]);

        Page::create([
            'title' => 'Çerez Kullanım Sözleşmesi',
        ]);

        Page::create([
            'title' => 'Müşteri Aydınlatma Metni',
        ]);
    }
}
